version: '3.8'

services:
  app:
    image: ayedyoussef777/foyer-app:${BUILD_NUMBER}  # Replace with your actual image
    container_name: spring-boot-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/foyer?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root  # Use a secure password
      - SERVER_PORT=8081
      - SERVER_CONTEXT_PATH=/Foyer
    ports:
      - "8081:8081"  # Expose the app on port 8081
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root  # Change this
      MYSQL_DATABASE: foyer  # Name of your database
      MYSQL_USER: your_user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
